In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv(r"fuel_prices_1970_2026.csv")
df.head()

         Date  Crude_Oil_Price
0  1970-01-01             1.21
1  1970-02-01             1.21
2  1970-03-01             1.21
3  1970-04-01             1.21
4  1970-05-01             1.21

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 675 entries, 0 to 674
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             675 non-null    str
 1   Crude_Oil_Price  675 non-null    float64
dtypes: float64(1), str(1)
memory usage: 10.7 KB

In [6]:
df.describe()

       Crude_Oil_Price
count       675.000000
mean         39.804040
std          30.611456
min           1.210000
25%          16.533333
50%          29.113333
75%          61.246667
max         132.825184

In [7]:
df.tail()

           Date  Crude_Oil_Price
670  2025-11-01            59.46
671  2025-12-01            57.95
672  2026-01-01            60.04
673  2026-02-01            64.47
674  2026-03-01            87.84